name: BitQuest
version: 1.1
author: The BitQuest Open Source Project
main: com.bitquest.bitquest.BitQuest
description: The Minecraft server that runs on Bitcoin
commands:
  addarea:
    description: "Adds area to the server"
    usage: /addarea <size> <name>
  delarea:
    description: "Deletes area from the server (Where currently standing)"
    usage: /delarea
  publicarea:
    description: "Makes area public; If already public reverts it to private"
    usage: /publicarea
  ban:
    description: "Adds player to the ban list"
    usage: /ban <nickname>
  unban:
    description: "Removes player from the ban list"
    usage: /unban <nickname>