name: BitQuest
version: 1.1
author: The BitQuest Open Source Project
main: com.bitquest.bitquest.BitQuest
description: The Minecraft server that runs on Bitcoin
commands:
  addarea:
    description: "Adds area to the server"
    usage: /addarea