language: java
jdk:
  - oraclejdk8
os:
  linux

env:

matrix:
  include:
    - script: mvn checkstyle:check -B
mvn checkstyle:
  allow_failures:
    - script: mvn checkstyle:check -B


cache:
  directories:
    $HOME/.m2/

script:
  mvn package -B

addons:
  apt:
    update: true
