spigot:
  container_name: bitquest
  build: .
  volumes:
    - "./target/BitQuest.jar:/spigot/plugins/BitQuest.jar"
  ports:
    - "25565:25565"
  environment:
    - BLOCKCYPHER_CHAIN=btc/test3
    - DENOMINATION_NAME=TestBits
  links:
    - redis
    - postgres
    - bitcoind
redis:
  image: redis
postgres:
  image: postgres
  environment:
    - POSTGRES_USER=bitquest
    - POSTGRES_PASSWORD=ORLY
bitcoind:
  image: mego/bitcoind
  environment:
    - USERNAME=wobble
    - PASSWORD=l1z4rdk1ng