spigot:
  extends:
    file: development.yml
    service: spigot
  container_name: bitquest
  environment:
    - BITQUEST_ENV=development
    - BLOCKCHAIN=btc/test3
    - BITCOIN_PUBLIC_KEY=tpubD6NzVbkrYhZ4Wwu2zXR4r2LAD87nLwqdKWBsH8qa2EkSbD5RSJARhCEKoBjuJAbig7aowS6gGJz9S6R77Yqf6DLE7qTFuT3ZV6ZZeKQGRs7
  build: .
  volumes:
    - "./build/libs/:/spigot/plugins"
    - ".:/bitquest"
  ports:
    - "25565:25565"
  links:
    - redis
redis:
  image: redis
