spigot:
  container_name: bitquest
  environment:
    - BITQUEST_ENV=development
    - BITCOIN_NODE_HOST=10.1.1.3
    - BITCOIN_NODE_USERNAME=alice
    - BITCOIN_NODE_PASSWORD=odonkor1
    - ADMIN_UUID=ae89b9c1-2d1d-4d0b-957d-1e5acd114e6e
  build: .
  volumes:
    - "./build/libs/:/spigot/plugins"
    - ".:/bitquest"
  ports:
    - "25565:25565"
  links:
    - redis
redis:
  image: redis
