spigot:
  container_name: bitquest
  build: .
  volumes:
    - "./plugins/BitQuest.jar:/spigot/plugins/BitQuest.jar"
  ports:
    - "25565:25565"
  links:
    - redis
    - postgres
redis:
  image: redis
postgres:
  image: postgres