spigot:
  extends:
    file: development.yml
    service: spigot
  container_name: bitquest
  environment:
    - BITQUEST_ENV=development
    - WORLD_ADDRESS=DLmU4E3qtGd74ku7hgCXZQ91RpvLdAVn4e
    - WORLD_PRIVATE_KEY=8c7ff7dfccf57d1b3f461725d609de77747d870e92f736eac7678724bb5db6da
  build: .
  volumes:
    - "./build/libs/:/spigot/plugins"
    - ".:/bitquest"
  ports:
    - "25565:25565"
  links:
    - redis
redis:
  image: redis
