spigot:
  container_name: bitquest
  build: .
  volumes:
    - "./target/BitQuest.jar:/spigot/plugins/BitQuest.jar"
  ports:
    - "25565:25565"
  links:
    - redis
    - postgres
    - bitcoin
redis:
  image: redis
postgres:
  image: postgres
  environment:
    - POSTGRES_USER=bitquest
    - POSTGRES_PASSWORD=ORLY
bitcoin:
  image: mego/bitcoin-core
  environment:
    - USERNAME=testnet
    - PASSWORD=testnet